# Generated by Django 5.1.6 on 2025-02-12 07:15

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_pic',
            field=models.ImageField(blank=True, default='', null=True, upload_to=users.models.User.user_profile_pic_path),
        ),
    ]
