# Generated by Django 5.1.6 on 2025-03-03 22:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='material',
            name='color',
        ),
        migrations.RemoveField(
            model_name='material',
            name='size',
        ),
    ]
