# Generated by Django 5.1.7 on 2025-03-20 11:05

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('materials', '0002_remove_material_color_remove_material_size'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseMaterial',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.IntegerField(default=0, verbose_name='Quantity')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Price')),
                ('color', models.CharField(max_length=255, verbose_name='Color')),
                ('size', models.CharField(max_length=255, verbose_name='Size')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Date')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materials.material', verbose_name='Material')),
            ],
        ),
    ]
